services:
  server:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_SERVER}:latest
    env_file: ".env"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  client:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_CLIENT}:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server
