services:
  server:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_SERVER}:${IMAGE_TAG}
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
      - URL=${URL}
      - MONGODB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
    ports:
      - 3000:3000

  client:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_CLIENT}:${IMAGE_TAG}
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - server
