services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
      - URL=${URL}
      - MONGODB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
    ports:
      - 3000:3000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server
