services:
  server:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_SERVER}:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=3000
      - CLIENT_PORT=80
      - URL=http://vital.rhamzthev.com
      - MONGODB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
    ports:
      - 3000:3000

  client:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_CLIENT}:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server
